// settings
export const TOGGLE_DEBUG = 'TOGGLE_DEBUG';

// layers
export const TOGGLE_OPTIONS_MENU = 'TOGGLE_OPTIONS_MENU';

// game
export const SET_REGION = 'SET_REGION';
export const SET_INITIAL_MARKERS = 'SET_INITIAL_MARKERS';
export const SET_MARKERS = 'SET_MARKERS';
export const SET_CORRECT_MARKER = 'SET_CORRECT_MARKER';
export const REMOVE_CORRECT_MARKER = 'REMOVE_CORRECT_MARKER';
